version: "3.3"

services:

  # Base de Datos MySQL
    mysql:
      image: mysql:8.0
      container_name: mysql
      volumes:
        - ./carmakers.sql:/docker-entrypoint-initdb.d/db.sql
      ports:
        - "3306"
      environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: carmakers
      networks:
      - app-network

  # Aplicacion Node
    app:
      container_name: nodeapp
      build:
        context: .
        dockerfile: DockerFile
      ports:
        - "4040:4040"
      volumes:
        - .:/app
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
        MYSQL_DB: carmakers
      depends_on:
        - mysql
      networks:
        - app-network
      
    # redes de los contenedores
    networks:
      app-network:
        driver: bridge